Add functional requirements
Kowalski1024/speech-to-text-tester pull request #2
Opened 2023-11-12 14:42 UTC by Gochad

2023-11-16 20:16 UTC, Kowalski1024 requested changes

2023-11-16 20:16 UTC, Kowalski1024 commented on apptests/feature/generators.feature
> +  Scenario: Make transcript for every video in data
I think, there should be more like "Returns information about available transcriptions".  
The [add_transcripts_info](https://github.com/Kowalski1024/Mi-Go/blob/master/generators/youtube_generator.py#L181C5-L181C25) returns only a list of languages in which transcriptions are available, divided into those added manually and those generated by YT. It's also response from api, so we don't transcibe video.

2023-11-16 20:16 UTC, Kowalski1024 commented on testrunners/tests/tests.py
>  class TranscriptDifference(TranscriptTest):
Please adjust to the latest changes. I have added a new class [DummyTest](https://github.com/Kowalski1024/Mi-Go/blob/master/testrunners/tests/tests.py#L14) that should allow you to test the framework itself without loading the model.

2023-11-21 09:11 UTC, Gochad commented on apptests/feature/generators.feature
> +  Scenario: Make transcript for every video in data
@Kowalski1024 i changed that

2023-11-21 09:11 UTC, Gochad commented on testrunners/tests/tests.py
>  class TranscriptDifference(TranscriptTest):
fix after rebase

2023-11-21 10:58 UTC, Kowalski1024 commented on testrunners/tests/tests.py
> +from apptests import TestModel
The changes from the tests.py file should be rolled back, as DummyTest can be used.

2023-11-21 10:58 UTC, Kowalski1024 commented on apptests/feature/all_project.feature
> +    Given model type
I would make it more general, like:
`Given arguments for a particular TranscriptTest`

Without model typle, language, etc.

2023-11-21 11:18 UTC, Gochad commented on apptests/feature/all_project.feature
> +    Given model type
done

2023-11-21 18:48 UTC, Kowalski1024 approved these changes

2023-11-21 18:48 UTC, merged